module: GatheredKit
author: Joseph Duffy
author_url: https://josephduffy.co.uk
github_url: https://github.com/josephduffy/GatheredKit
github_file_prefix: https://github.com/JosephDuffy/GatheredKit/tree/master
readme: docs/README.md