os: osx
language: swift

cache:
  bundler: true
  directories:
    - Carthage

before_install:
  - brew outdated carthage || brew upgrade carthage

install:
  - bundle install
  - bundle exec fastlane install_dependencies

script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bundle exec fastlane perform_pr_checks; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec fastlane test; fi

before_deploy:
  - carthage build --no-skip-current
  - carthage archive GatheredKit
  # Based on https://docs.travis-ci.com/user/deployment/releases/ to automatically tag, but modified to use the merger's credentials
  - git config --local user.name "$(git log -1 --pretty=format:'%an')"
  - git config --local user.email "$(git log -1 --pretty=format:'%ae')"
  - git tag "v$(defaults read "$(pwd)/Source/Info.plist" CFBundleShortVersionString)"

deploy:
  - provider: releases
    api_key:
      secure: bIwZ3lrjk+w8TDdYy93bntSx9vC2KQa11L70w8K9KTraOF7cpR7vge8zvV3ppsznpQfv10T2QplVN0nVQ/SWfbfl5Z0bErM+iLULfL9bc3wnlVMqL4BK4WAUVdC8lWpD/A+3o72/CkH59vvTvTk15OPz76Uw0Js+wLTfGUFXI/lfsfo/x94i6t4Ms571c4YacEMLhKuGs9/cjuhSB3dXX3RqYgGmuysLXpP1kzFs94aY1/EZtNDw+ieM4lYCgMKV7jad0RRBkJthlvwnawNFbo+0fcrVrByDIH9hZ9iSbNKnYYuijCp2VWsl3o1miG8ch+HlyI6eyIQUI52wO5h+1DOyjU6p+3IK21e84omeBLlrhxAGoRbw9cp8EbC4+dYgCuSXhqEKPECXMytuj2TOIWz7rZXRd5U0GbI4S9aRruqB6tx+yByGpC9YFfDlytNGyhDQllZOjyioppP5bHM4AoABGIuwTCwC9x1viDg9XtpO/zG1/mKjUhGXXZnI7gWn/PjDgW53exNZ1IXhGRCAMxKcUqVjksA1HxVDi89yjtZqSORBijjGwUvHLysXRhabSSqAb9bkOLM2MFNekp1nJVDEOmoYWC7sJD7SjaabxvmwGruA9K7pRSSg5ovVW+aaHZpa1JmCGLd/TcHEpFiWqWRTyz/EIGMHylnb7hkQD0M=
    file: GatheredKit.framework.zip
    skip_cleanup: true
    on:
      tags: true
      repo: JosephDuffy/GatheredKit
  - provider: script
    script: pod trunk push
    skip_cleanup: true
    on:
      tags: true
      repo: JosephDuffy/GatheredKit

env:
  global:
    # CocoaPods
    secure: wtXd2k+2WJeQH6MXdvwsaaXLIzIQ3ZjIwtCOt7YHouLxhKyAdjEgjHik7UPq3vnSJtEYfXNDT8P0zJL4AXHTTaekwrxUBzdoO0UOoEBOebMwcmCKd1W8903jw2LGBg1xRpasEEWPplS9/MGqDIe1bMPXKXrLZ6TjvWRKR4zQkMknXbuRmpu18tpd60pYX84rpk+umh0vSwmUFXLhySdo4D8bPdKDZD9CzPl6Gjk9O/GPGF3hqECZhkQLS2ZZePdkxfiG0TI6AFGx/HLmgwsrvpsge4bUC4ytEBZ9OeqtsDme5YcakqHY6+4vqxyOkq1oWMJTzPlE7g2+1ZltcLTpbznYDlw81E2gM/1MzX7qzFFe7uTuQ6CQDgjFTsekMo12yQWDvjsdk3W/iWraTguJjBCgQp+d0cfdwk3j8/6CQia8dhz2jAbpfLVEBhs8f3zzwQhbtaHkYhm/6585u6MfvpJie73BFUyL3wp9WDfVkv/PrmqY3ERstOKAXyoBMgmJR813ZGmg2RX5Ia0gNBlsotSsB03N2ZJGTDmVxaiugJniUK3AOvloO25rl4RIe090M89373ntcIjKQaZXE+4W1/umsIJN2jpD73WVfjK8VOs2yUKZtxD9XLqtGCLfOiRy0/xQDhUy77o4CVzK+fT2Mm2CJVPYdymep/pDpCV3wdo=