os: osx
language: swift

cache:
  bundler: true
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage

install:
  - bundle install
  - bundle exec fastlane install_dependencies

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then bundle exec fastlane perform_pr_checks; fi

before_deploy:
  - carthage build --platform iOS --archive
  # Based on https://docs.travis-ci.com/user/deployment/releases/ to automatically tag, but modified to use the merger's credentials
  - git config --local user.name "$(git log -1 --pretty=format:'%an')"
  - git config --local user.email "$(git log -1 --pretty=format:'%ae')"
  - git tag "v$(defaults read "$(pwd)/Source/Info.plist" CFBundleShortVersionString)" || true

deploy:
  - provider: releases
    api_key:
      secure: GxXxOohlCmDDyfBJc2EspvXBAVCum5gSeLoWbbXJboiZsuQdW5TO0kBmf7kjgqzpPlZT7M50imlguQb03XekpSG/B1dqfv0g8MR6bephcfHjzJf6hhBemDmHXxidZdFULv7RDdJ3Uo+cLfnLYYrI90gRAemPUbgQCxfrmQyBzavn81mp2e3j/ZHgttyQ+hqKVFNIJ6Bgdsm8/nD2wXUGskN8/SoJJCa/PdmF3Eb0F6lhpd/iWY6CERk2fuzd4ZKCCJuv4ceF/Tp9skPZ607446AB7Ey8dkxvpsoNGSn4mpGddFLalWAX0+fCoCCT8cUrPf/5skTCRolV+qjH7t8sJ4TIZ2bdUzySrURSQnHQvCjBMiukpFPe4d4KdMhM2eeqQbAMOh9lAVH1LT+4V6+meJSicWeLRMZ/zApV/BDnBJ8If2qwWAuIPb7rnuGhwKJo74bZPqqeVvl+fPYhz3b2bH6TSR53a9TeeWZcXBLG16RMh0xeKrvXb/63EW17GSSiHRPCLuMGEENbumIUEPY4S49n3CKmhupwVoRJcjoJhVyz2xxw02fUGYbc52YbogUjXmSfbWI5+vICaQbntaQtuxNMtI0ut5pWtsB8+280C829ZfaZSyhILwfLHOL5yD10kj+qtiM2n2iyKjvkq9MTnFyx0otvUTu4bWacmHJ2sqw=
    file: GatheredKit.framework.zip
    skip_cleanup: true
    on:
      repo: JosephDuffy/GatheredKit
  - provider: script
    script: pod trunk push
    skip_cleanup: true
    on:
      repo: JosephDuffy/GatheredKit

env:
  global:
    # CocoaPods
    secure: wtXd2k+2WJeQH6MXdvwsaaXLIzIQ3ZjIwtCOt7YHouLxhKyAdjEgjHik7UPq3vnSJtEYfXNDT8P0zJL4AXHTTaekwrxUBzdoO0UOoEBOebMwcmCKd1W8903jw2LGBg1xRpasEEWPplS9/MGqDIe1bMPXKXrLZ6TjvWRKR4zQkMknXbuRmpu18tpd60pYX84rpk+umh0vSwmUFXLhySdo4D8bPdKDZD9CzPl6Gjk9O/GPGF3hqECZhkQLS2ZZePdkxfiG0TI6AFGx/HLmgwsrvpsge4bUC4ytEBZ9OeqtsDme5YcakqHY6+4vqxyOkq1oWMJTzPlE7g2+1ZltcLTpbznYDlw81E2gM/1MzX7qzFFe7uTuQ6CQDgjFTsekMo12yQWDvjsdk3W/iWraTguJjBCgQp+d0cfdwk3j8/6CQia8dhz2jAbpfLVEBhs8f3zzwQhbtaHkYhm/6585u6MfvpJie73BFUyL3wp9WDfVkv/PrmqY3ERstOKAXyoBMgmJR813ZGmg2RX5Ia0gNBlsotSsB03N2ZJGTDmVxaiugJniUK3AOvloO25rl4RIe090M89373ntcIjKQaZXE+4W1/umsIJN2jpD73WVfjK8VOs2yUKZtxD9XLqtGCLfOiRy0/xQDhUy77o4CVzK+fT2Mm2CJVPYdymep/pDpCV3wdo=