os: osx
language: swift

cache:
  bundler: true
  directories:
    - Carthage

before_install:
  - brew outdated carthage || brew upgrade carthage

install:
  - bundle install
  - bundle exec fastlane install_dependencies

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then bundle exec fastlane perform_pr_checks; fi

before_deploy:
  - carthage build --no-skip-current
  - carthage archive GatheredKit
  # Based on https://docs.travis-ci.com/user/deployment/releases/ to automatically tag, but modified to use the merger's credentials
  - git config --local user.name "$(git log -1 --pretty=format:'%an')"
  - git config --local user.email "$(git log -1 --pretty=format:'%ae')"
  - git tag "v$(defaults read "$(pwd)/Source/Info.plist" CFBundleShortVersionString)"

deploy:
  - provider: releases
    api_key:
      secure: afKyBHFezn853gDksozT18t183hwRXUj78Kg8VfjMtBF5sHOAulAM11vcUP8q2KAzkivjsAZoGWGunJZDPoMSWiWDJZVaXEu2KerqixAgxbIJobtHg2c9iAfJhCIsmAubL8yrJhare2ALtHSxcT2W8ji6QnBlSlOXeqKDhdkstXvD2m8ahqXeuJHNDffMABaaZefr7OjPA8yTU7dQ3pK1047f5AXLan+921CQSgylq3qU416JU9TbDGVJ9IGuk2KaHIzAUJgxZVzjvy8KRDydhoH6FLISRX5aUjpr5pukqqx5c1dg8q1oaSiPoSgo2Nw8qzP8GckA4p/vepZlDrEdcKtBHqWB+hXSqlz/XgntYQYaUpm7QRRXMf2prHgo28mNhctPlsTXByBetDkls3jIMSyl26mXRABftTzB9RYA/iq00+1ugVyOx/PBgSIMLC3Qc9qHVVXsiRMJE1iiPzNDDQzw+5Ym+H/0gdYM0rKEbTTXqFKXDjXer/QM2SWeLsyBMOImAKiabFaDzCwhq8qM5lc2oK4iIew/3CqCmFJ6t8ZGU+VBiEQmeF8mfkBtiAFx/Z57H1AI4tyz9p9Qy7irwPfYV2MlYCBMhXNXLRJlXe2kPAHCL4HpKwSQlmo8NG8+NGPjtWy4UuX5HwYKLNAKhpZu6Zc4+TFFoR9M9bL+Gg=
    file: GatheredKit.framework.zip
    skip_cleanup: true
    on:
      repo: JosephDuffy/GatheredKit
  - provider: script
    script: pod trunk push
    skip_cleanup: true
    on:
      repo: JosephDuffy/GatheredKit

after_deploy:
  - git push origin --tags

env:
  global:
    # CocoaPods
    secure: wtXd2k+2WJeQH6MXdvwsaaXLIzIQ3ZjIwtCOt7YHouLxhKyAdjEgjHik7UPq3vnSJtEYfXNDT8P0zJL4AXHTTaekwrxUBzdoO0UOoEBOebMwcmCKd1W8903jw2LGBg1xRpasEEWPplS9/MGqDIe1bMPXKXrLZ6TjvWRKR4zQkMknXbuRmpu18tpd60pYX84rpk+umh0vSwmUFXLhySdo4D8bPdKDZD9CzPl6Gjk9O/GPGF3hqECZhkQLS2ZZePdkxfiG0TI6AFGx/HLmgwsrvpsge4bUC4ytEBZ9OeqtsDme5YcakqHY6+4vqxyOkq1oWMJTzPlE7g2+1ZltcLTpbznYDlw81E2gM/1MzX7qzFFe7uTuQ6CQDgjFTsekMo12yQWDvjsdk3W/iWraTguJjBCgQp+d0cfdwk3j8/6CQia8dhz2jAbpfLVEBhs8f3zzwQhbtaHkYhm/6585u6MfvpJie73BFUyL3wp9WDfVkv/PrmqY3ERstOKAXyoBMgmJR813ZGmg2RX5Ia0gNBlsotSsB03N2ZJGTDmVxaiugJniUK3AOvloO25rl4RIe090M89373ntcIjKQaZXE+4W1/umsIJN2jpD73WVfjK8VOs2yUKZtxD9XLqtGCLfOiRy0/xQDhUy77o4CVzK+fT2Mm2CJVPYdymep/pDpCV3wdo=