language: swift
osx_image: xcode9.3

cache:
  bundler: true
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage

script:
  - bundle exec fastlane install_dependencies
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bundle exec fastlane perform_pr_checks; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec fastlane test; fi'
