os: osx
language: swift

cache:
  bundler: true
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage

install:
  - bundle install
  - bundle exec fastlane install_dependencies

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then bundle exec fastlane perform_pr_checks; fi

before_deploy:
  - carthage build --platform iOS --archive
  # Based on https://docs.travis-ci.com/user/deployment/releases/ to automatically tag, but modified to use the merger's credentials
  - git config --local user.name "$(git log -1 --pretty=format:'%an')"
  - git config --local user.email "$(git log -1 --pretty=format:'%ae')"
  - git tag "v$(defaults read "$(pwd)/Source/Info.plist" CFBundleShortVersionString)" || true

deploy:
  - provider: releases
    api_key:
      secure: gL5I7gh7UR8qt+b+2HS5lfY/ExJIchxI/bqGaIdZsbQfs7jIqEeRBVgltxZHIzHoBdugjU2kSqS6XgfHbO30puaWIgFkWGK1mmhijThOr7M8bv0i5k/nJaGGt3Phc/G9mMArVx/4WIs3nPwareBN/CRSNKir2eYp/041GX4jvqqTgp2nqzb2feZpwXjBEn6fHS5gxw2qEYbi9rM64/9qdHUqOjyQzIlI7Wiw8GTOtuWfNbWL2t6bAhkXoX/T5IGx6n8GXRJbbXSPqjtkG/Zl4bO370g43bPv9WJi0iTZIIvmxuzY+dCw8T30MtpzSDUnsNdspVrxsnVaq1uRtZiQDO42l/MiB5UTx+CyCkyNwmy2qNG2kVRHY5YRoc/Fw+Q7/1yz+tmAgx77gmtOY8si6q4b7x/apD1TYcip2aW31c8imli7YBrNRI85VoD1XhxRS4elPuFS8c36lAWdjkY70MAotEn0KN14/2QqbYv1v7ILKrkgXbmLY3AeWfr/1HePQAbBfwHOnGbUdysQqsszFGJxGDfrMKyrjklxHiAYe7USRe4kVBJgUTkQiISlP0HukgY27Z7q7Oqg72a/klXHpEbhKRtHGcQT5fYOTPP7cDypCKZER2kZZ2HmFMBBRjCCzs2yPzxX456anNIdqTQxfngFCtHK3Z2lGfrFNBL/UAU=
    file: GatheredKit.framework.zip
    skip_cleanup: true
    on:
      repo: JosephDuffy/GatheredKit
  - provider: script
    script: pod trunk push
    skip_cleanup: true
    on:
      repo: JosephDuffy/GatheredKit

env:
  global:
    # CocoaPods
    secure: wtXd2k+2WJeQH6MXdvwsaaXLIzIQ3ZjIwtCOt7YHouLxhKyAdjEgjHik7UPq3vnSJtEYfXNDT8P0zJL4AXHTTaekwrxUBzdoO0UOoEBOebMwcmCKd1W8903jw2LGBg1xRpasEEWPplS9/MGqDIe1bMPXKXrLZ6TjvWRKR4zQkMknXbuRmpu18tpd60pYX84rpk+umh0vSwmUFXLhySdo4D8bPdKDZD9CzPl6Gjk9O/GPGF3hqECZhkQLS2ZZePdkxfiG0TI6AFGx/HLmgwsrvpsge4bUC4ytEBZ9OeqtsDme5YcakqHY6+4vqxyOkq1oWMJTzPlE7g2+1ZltcLTpbznYDlw81E2gM/1MzX7qzFFe7uTuQ6CQDgjFTsekMo12yQWDvjsdk3W/iWraTguJjBCgQp+d0cfdwk3j8/6CQia8dhz2jAbpfLVEBhs8f3zzwQhbtaHkYhm/6585u6MfvpJie73BFUyL3wp9WDfVkv/PrmqY3ERstOKAXyoBMgmJR813ZGmg2RX5Ia0gNBlsotSsB03N2ZJGTDmVxaiugJniUK3AOvloO25rl4RIe090M89373ntcIjKQaZXE+4W1/umsIJN2jpD73WVfjK8VOs2yUKZtxD9XLqtGCLfOiRy0/xQDhUy77o4CVzK+fT2Mm2CJVPYdymep/pDpCV3wdo=