os: osx
osx_image: xcode10.1
language: swift

cache:
  bundler: true
  directories:
    - Carthage
    - $HOME/Library/Caches/Homebrew

before_install:
  - brew outdated carthage || brew upgrade carthage

install:
  - bundle install --deployment
  - bundle exec fastlane install_dependencies

script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bundle exec fastlane perform_pr_checks; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec fastlane test; fi

before_deploy:
  - carthage build --archive --cache-builds --platform iOS

deploy:
  - provider: releases
    api_key:
      secure: nQcTlWICYlK8eUo8SLi+OHs3H+THhkTpKdT0pemDdo1CMXJruvB96Ok6yJ5qfUp3A5bigqR9Cxe2XEgwkutK7Zmq+q+XwPh3bWyn8A6UkeDpeCLiwae0pNdQ5Dbfb6qoNF4zujburaJ29wfpbKY+iQ+DDOMhfQi05nMrcbAjReI+r0wBvpLJc2tY0XBnSloapHJbuiU/2Xy2EHc0ZS/weQNioXfKWhRx4LDhXVhpa5q9UH/Z/wSJLD5/L+MofHiVBcj6uFg9Rv42FyiBpPFEO9tjFHtE00cQJmQl21Tn7Y67OhUSzAJ9gvMkXbqOwFQE/K3iKpVDL2uiIMCNDIphR1FIeim7b3V390/1RBkdXaU9UfF9mNu/6HMgHKmfkSwg55kTm7GeROVd6aF/yVf28I+XXhz9Z/w5vq8o+gzQz9XWFDMr9Dla6IF1RpnAtL/qzIYtktX51aK7lKlypk83D4HRT7doQ6+5Qww/pEoeX06GjkxspThpSppvsNbzJ1cTUFwyWD5Mq8if3F47848oSK2E2etJAQsxdLshz6syLqvTK3Y42C5fyUyz+B7D4mXaMnUNuU97rzlnsSzogxlgAvPhn+8OlIBN7ngMPzzho211gmY7eBnnyIFgWxblrmoX6aCOQdakSHN1pFIj4WQYFTQmWgIKrJPkYa7w0tx9hLI=
    file: GatheredKit.framework.zip
    skip_cleanup: true
    prerelease: true
    on:
      repo: JosephDuffy/GatheredKit
      tags: true
  - provider: script
    script: pod trunk push
    skip_cleanup: true
    on:
      repo: JosephDuffy/GatheredKit
      tags: true

env:
  global:
    # CocoaPods
    secure: wtXd2k+2WJeQH6MXdvwsaaXLIzIQ3ZjIwtCOt7YHouLxhKyAdjEgjHik7UPq3vnSJtEYfXNDT8P0zJL4AXHTTaekwrxUBzdoO0UOoEBOebMwcmCKd1W8903jw2LGBg1xRpasEEWPplS9/MGqDIe1bMPXKXrLZ6TjvWRKR4zQkMknXbuRmpu18tpd60pYX84rpk+umh0vSwmUFXLhySdo4D8bPdKDZD9CzPl6Gjk9O/GPGF3hqECZhkQLS2ZZePdkxfiG0TI6AFGx/HLmgwsrvpsge4bUC4ytEBZ9OeqtsDme5YcakqHY6+4vqxyOkq1oWMJTzPlE7g2+1ZltcLTpbznYDlw81E2gM/1MzX7qzFFe7uTuQ6CQDgjFTsekMo12yQWDvjsdk3W/iWraTguJjBCgQp+d0cfdwk3j8/6CQia8dhz2jAbpfLVEBhs8f3zzwQhbtaHkYhm/6585u6MfvpJie73BFUyL3wp9WDfVkv/PrmqY3ERstOKAXyoBMgmJR813ZGmg2RX5Ia0gNBlsotSsB03N2ZJGTDmVxaiugJniUK3AOvloO25rl4RIe090M89373ntcIjKQaZXE+4W1/umsIJN2jpD73WVfjK8VOs2yUKZtxD9XLqtGCLfOiRy0/xQDhUy77o4CVzK+fT2Mm2CJVPYdymep/pDpCV3wdo=