import CoreLocation

public typealias LocationAuthorizationValue = Property<CLAuthorizationStatus, LocationAuthorizationFormatter>
public typealias OptionalLocationAuthorizationValue = OptionalProperty<CLAuthorizationStatus?, LocationAuthorizationFormatter>
