#if canImport(CoreMotion)
import CoreMotion

public typealias MagneticFieldCalibrationAccuracyValue = Property<CMMagneticFieldCalibrationAccuracy, MagneticFieldCalibrationAccuracyFormatter>
public typealias OptionalMagneticFieldCalibrationAccuracyValue = OptionalProperty<CMMagneticFieldCalibrationAccuracy?, MagneticFieldCalibrationAccuracyFormatter>
#endif
