import Foundation
import GatheredKit

public typealias ProcessInfoThermalStateProperty = BasicProperty<ProcessInfo.ThermalState, ProcessInfoThermalStateFormatter>
public typealias OptionalProcessInfoThermalStateProperty = BasicProperty<ProcessInfo.ThermalState?, ProcessInfoThermalStateFormatter>
