import CoreLocation
import GatheredKit

public typealias CLLocationAuthorizationProperty = BasicProperty<CLAuthorizationStatus>
public typealias OptionalCLLocationAuthorizationProperty = BasicProperty<CLAuthorizationStatus?>
