//
//  DataSourceData.swift
//  GatheredKit
//
//  Created by Joseph Duffy on 03/02/2017.
//  Copyright © 2017 Joseph Duffy. All rights reserved.
//

import Foundation

/**
 A piece of data generated by a `DataSource`
 */
public struct DataSourceData {

    /// A user-friendly name for the data source
    public let displayName: String

    /// The data source that supplied the data
    public let dataSource: DataSource.Type

    /// The unmodified, unformatted, original value
    public let rawValue: Any?

    /// A human-readable formatted value
    /// Note that this may differ from the result of `unit.formattedString(for:)`
    public let formattedValue: String?

    /// A unit of measurement for the data source's value
    public let unit: DataSourceDataUnit?

    /**
     Create a new `DataSourceData`
     
     - parameter displayName: A user-friendly name for the data source
     - parameter dataSource: The data source that supplied the data
     - parameter rawValue: The unmodified, unformatted, original value
     - parameter formattedValue: A human-readable formatted value. Default is `nil`
     - parameter unit: A unit of measurement for the data source's value. Default is `nil`
     */
    init(displayName: String, dataSource: DataSource.Type, rawValue: Any?, formattedValue: String? = nil, unit: DataSourceDataUnit? = nil) {
        self.displayName = displayName
        self.dataSource = dataSource
        self.rawValue = rawValue
        self.formattedValue = formattedValue
        self.unit = unit
    }

}
