import AVFoundation
import GatheredKit

public typealias AVCaptureDevicePosition = BasicProperty<AVCaptureDevice.Position, AVCaptureDevicePositionFormatter>
public typealias OptionalAVCaptureDevicePosition = BasicProperty<AVCaptureDevice.Position?, AVCaptureDevicePositionFormatter>
