import AVFoundation
import GatheredKit

public typealias AVCaptureDevicePositionProperty = BasicProperty<AVCaptureDevice.Position, AVCaptureDevicePositionFormatter>
public typealias OptionalAVCaptureDevicePositionProperty = BasicProperty<AVCaptureDevice.Position?, AVCaptureDevicePositionFormatter>
