import CoreLocation

public typealias LocationAuthorizationValue = Value<CLAuthorizationStatus, LocationAuthorizationFormatter>
public typealias OptionalLocationAuthorizationValue = Value<CLAuthorizationStatus?, LocationAuthorizationFormatter>
