import CoreMotion

public final class MagneticFieldCalibrationAccuracyValue: Property<CMMagneticFieldCalibrationAccuracy, MagneticFieldCalibrationAccuracyFormatter> { }
public final class OptionalMagneticFieldCalibrationAccuracyValue: OptionalProperty<CMMagneticFieldCalibrationAccuracy?, MagneticFieldCalibrationAccuracyFormatter> { }
