import CoreMotion

public final class MagneticFieldCalibrationAccuracyValue: Value<CMMagneticFieldCalibrationAccuracy, MagneticFieldCalibrationAccuracyFormatter> { }
public final class OptionalMagneticFieldCalibrationAccuracyValue: OptionalValue<CMMagneticFieldCalibrationAccuracy?, MagneticFieldCalibrationAccuracyFormatter> { }
